# Generated by Django 4.1 on 2022-09-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_rename_comentario_comentarios_delete_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('imag', models.ImageField(blank=True, help_text='Seleccione una imagen para mostrar', null=True, upload_to='img/evento')),
                ('fecha', models.DateField()),
                ('fecha_public', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
