# Generated by Django 4.1 on 2022-09-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cargo',
            field=models.BooleanField(default=False),
        ),
    ]
